import { theme as antdTheme, type ThemeConfig } from 'antd'

export const lightTheme: ThemeConfig = {
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    colorPrimary: '#b0c2d8',
    colorSuccess: '#00b42a',
    colorWarning: '#ff7d00',
    colorError: '#f53f3f',
    colorInfo: '#0a63c9',
    colorPrimaryBg: '#f0f5fa',
    colorPrimaryBgHover: '#e5ecf6',
    colorPrimaryBorder: '#b0c2d8',
    colorPrimaryBorderHover: '#9db5ce',
    colorPrimaryHover: '#bccde0',
    colorPrimaryActive: '#9db5ce',
    colorPrimaryText: '#8fa5bf',
    colorPrimaryTextHover: '#80979b',
    colorPrimaryTextActive: '#718cb0',
    colorBgBase: '#e9edf1',
    colorBgContainer: '#f4f7fa',
    colorBgElevated: '#f2f5f8',
    colorBgLayout: '#e1e7ee',
    colorTextBase: '#1f2937',
    colorText: 'rgba(31, 41, 55, 0.92)',
    colorTextSecondary: 'rgba(31, 41, 55, 0.72)',
    colorTextTertiary: 'rgba(31, 41, 55, 0.56)',
    colorBorder: '#aebdcb',
    colorBorderSecondary: '#c0cdd9',
    colorSplit: '#b4c2cf',
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, 'Helvetica Neue', Arial, sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,
    lineHeight: 1.5714,
    padding: 20,
    paddingLG: 28,
    paddingSM: 16,
    paddingXS: 8,
    margin: 20,
    marginLG: 28,
    marginSM: 16,
    marginXS: 8,
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    borderRadiusXS: 4,
    lineWidth: 1,
    lineType: 'solid',
    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    boxShadow: '0 4px 20px -8px rgba(15, 23, 42, 0.12)',
    boxShadowSecondary: '0 10px 30px -12px rgba(15, 23, 42, 0.14)',
  },
  components: {
    Card: {
      colorBgContainer: '#f4f7fa',
      headerBg: 'transparent',
      colorBorderSecondary: '#b9c7d4',
      boxShadowTertiary: '0 8px 24px -14px rgba(15, 23, 42, 0.16)',
    },
    Modal: {
      contentBg: '#f4f7fa',
      headerBg: 'transparent',
    },
    Button: {
      borderRadius: 12,
      primaryShadow: '0 6px 18px -8px rgba(176, 194, 216, 0.52)',
    },
    Input: {
      borderRadius: 12,
      colorBgContainer: '#f4f7fa',
      activeBg: '#f4f7fa',
      activeBorderColor: '#5d86bd',
      hoverBorderColor: '#87a8d0',
    },
    Select: {
      borderRadius: 12,
      colorBgContainer: '#f4f7fa',
      optionSelectedBg: '#dbe5f1',
      optionActiveBg: '#e7edf5',
      optionSelectedColor: '#1f2937',
    },
    DatePicker: {
      borderRadius: 12,
      colorBgContainer: '#f4f7fa',
      cellHoverBg: '#e7edf5',
      cellActiveWithRangeBg: '#dbe5f1',
    },
    InputNumber: {
      borderRadius: 12,
      colorBgContainer: '#f4f7fa',
    },
    Layout: {
      siderBg: '#f4f7fa',
      headerBg: '#f4f7fa',
      bodyBg: '#e1e7ee',
      footerBg: '#e1e7ee',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#b0c2d8',
      itemSelectedColor: '#1f3a52',
      itemHoverBg: 'rgba(176,194,216,0.12)',
      darkItemBg: 'transparent',
      darkItemSelectedBg: '#b0c2d8',
      darkItemSelectedColor: '#1f3a52',
      darkItemHoverBg: 'rgba(176,194,216,0.12)',
    },
    Table: {
      borderColor: '#b4c2cf',
      headerBg: '#e7edf3',
      headerColor: 'rgba(17, 24, 39, 0.96)',
      rowHoverBg: '#eef3f7',
      headerSplitColor: '#b4c2cf',
      footerBg: '#eff4f8',
      cellPaddingBlock: 10,
      cellPaddingInline: 14,
      cellPaddingBlockMD: 8,
      cellPaddingInlineMD: 12,
      cellPaddingBlockSM: 6,
      cellPaddingInlineSM: 10,
    },
  },
}