import { theme as antdTheme, type ThemeConfig } from 'antd'

export const lightTheme: ThemeConfig = {
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    colorPrimary: '#b0c2d8',
    colorSuccess: '#00b42a',
    colorWarning: '#ff7d00',
    colorError: '#f53f3f',
    colorInfo: '#0a63c9',
    colorPrimaryBg: '#f0f5fa',
    colorPrimaryBgHover: '#e5ecf6',
    colorPrimaryBorder: '#b0c2d8',
    colorPrimaryBorderHover: '#9db5ce',
    colorPrimaryHover: '#bccde0',
    colorPrimaryActive: '#9db5ce',
    colorPrimaryText: '#8fa5bf',
    colorPrimaryTextHover: '#80979b',
    colorPrimaryTextActive: '#718cb0',
    colorBgBase: '#f7f9fb',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#eef2f6',
    colorTextBase: '#374151',
    colorText: 'rgba(55, 65, 81, 0.88)',
    colorTextSecondary: 'rgba(55, 65, 81, 0.65)',
    colorTextTertiary: 'rgba(55, 65, 81, 0.45)',
    colorBorder: '#b5c1cd',
    colorBorderSecondary: '#c8d3df',
    colorSplit: '#bcc8d5',
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, 'Helvetica Neue', Arial, sans-serif",
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,
    lineHeight: 1.5714,
    padding: 20,
    paddingLG: 28,
    paddingSM: 16,
    paddingXS: 8,
    margin: 20,
    marginLG: 28,
    marginSM: 16,
    marginXS: 8,
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    borderRadiusXS: 4,
    lineWidth: 1,
    lineType: 'solid',
    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    boxShadow: '0 4px 20px -8px rgba(15, 23, 42, 0.12)',
    boxShadowSecondary: '0 10px 30px -12px rgba(15, 23, 42, 0.14)',
  },
  components: {
    Card: {
      colorBgContainer: '#ffffff',
      headerBg: 'transparent',
      colorBorderSecondary: '#bcc8d5',
      boxShadowTertiary: '0 8px 24px -14px rgba(15, 23, 42, 0.16)',
    },
    Modal: {
      contentBg: '#ffffff',
      headerBg: 'transparent',
    },
    Button: {
      borderRadius: 12,
      primaryShadow: '0 6px 18px -8px rgba(176, 194, 216, 0.52)',
    },
    Input: {
      borderRadius: 12,
      colorBgContainer: '#ffffff',
      activeBg: '#ffffff',
      activeBorderColor: '#5d86bd',
      hoverBorderColor: '#87a8d0',
    },
    Select: {
      borderRadius: 12,
      colorBgContainer: '#ffffff',
      optionSelectedBg: '#e5ecf6',
      optionActiveBg: '#edf3f9',
      optionSelectedColor: '#1f3a52',
    },
    DatePicker: {
      borderRadius: 12,
      colorBgContainer: '#ffffff',
      cellHoverBg: '#edf3f9',
      cellActiveWithRangeBg: '#e5ecf6',
    },
    InputNumber: {
      borderRadius: 12,
      colorBgContainer: '#ffffff',
    },
    Layout: {
      siderBg: '#ffffff',
      headerBg: '#ffffff',
      bodyBg: '#eef2f6',
      footerBg: '#eef2f6',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: '#b0c2d8',
      itemSelectedColor: '#1f3a52',
      itemHoverBg: 'rgba(176,194,216,0.12)',
      darkItemBg: 'transparent',
      darkItemSelectedBg: '#b0c2d8',
      darkItemSelectedColor: '#1f3a52',
      darkItemHoverBg: 'rgba(176,194,216,0.12)',
    },
    Table: {
      borderColor: '#bcc8d5',
      headerBg: '#f1f5f9',
      headerColor: 'rgba(31, 41, 55, 0.92)',
      rowHoverBg: '#f7fafc',
      headerSplitColor: '#bcc8d5',
      footerBg: '#f8fbfd',
      cellPaddingBlock: 10,
      cellPaddingInline: 14,
      cellPaddingBlockMD: 8,
      cellPaddingInlineMD: 12,
      cellPaddingBlockSM: 6,
      cellPaddingInlineSM: 10,
    },
  },
}